### ISSUE TITLE
cant run...

### ISSUE THREAD

**Issue by kkurt** [florianbgt/markbet#2]
I have just clonned repo but cant run after npm install.

> [Vue warn]: Property "$t" was accessed during render but is not defined on instance.
> [Vue warn]: Unhandled error during execution of render function
>   at <RouterLink to="/" activeClass=undefined exactActiveClass=undefined  ... >
> [nuxt] [request error] __vite_ssr_import_2__.default is not a function
>   at /c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:3699:60
>   at fn (/c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:400:27)
>   at Object.callAsync (/c:/tmp/test/markbet/node_modules/unctx/dist/index.mjs:41:19)
>   at callWithNuxt (/c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:402:23)
>   at applyPlugin (/c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:357:29)
>   at Module.applyPlugins (/c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:367:11)
>   at async createNuxtAppServer (/c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:46:7)
>   at async Object.renderToString (/c:/tmp/test/markbet/node_modules/vue-bundle-renderer/dist/index.mjs:264:19)
>   at async /c:/tmp/test/markbet/.nuxt/dev/index.mjs:468:20
>   at async /c:/tmp/test/markbet/node_modules/h3/dist/index.mjs:420:19
> [nitro] [dev] [unhandledRejection] TypeError: _ctx.$t is not a function
>     at file:///c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:11407:92
>     at renderFnWithContext (c:\tmp\test\markbet\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:847:21)
>     at Module.renderSlot (c:\tmp\test\markbet\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:2958:55)
>     at file:///c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:3450:35
>     at Proxy.renderFnWithContext (c:\tmp\test\markbet\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:847:21)
>     at Proxy.<anonymous> (c:\tmp\test\markbet\node_modules\vue-router\dist\vue-router.cjs.js:2166:60)
>     at renderComponentRoot (c:\tmp\test\markbet\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:890:44)
>     at renderComponentSubTree (c:\tmp\test\markbet\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:259:51)    at renderComponentVNode (c:\tmp\test\markbet\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:188:16)
>     at renderVNode (c:\tmp\test\markbet\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:295:22)
> [Vue Router warn]: No match found for location with path "/favicon.ico"
> [Vue Router warn]: No match found for location with path "/favicon.ico"
> [Vue warn]: Property "$t" was accessed during render but is not defined on instance.
> [Vue warn]: Unhandled error during execution of render function
>   at <RouterLink to="/" activeClass=undefined exactActiveClass=undefined  ... >
> [nuxt] [request error] __vite_ssr_import_2__.default is not a function
>   at /c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:3699:60
>   at fn (/c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:400:27)
>   at Object.callAsync (/c:/tmp/test/markbet/node_modules/unctx/dist/index.mjs:41:19)
>   at callWithNuxt (/c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:402:23)
>   at applyPlugin (/c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:357:29)
>   at Module.applyPlugins (/c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:367:11)
>   at processTicksAndRejections (node:internal/process/task_queues:96:5)
>   at async createNuxtAppServer (/c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:46:7)
>   at async Object.renderToString (/c:/tmp/test/markbet/node_modules/vue-bundle-renderer/dist/index.mjs:264:19)
>   at async /c:/tmp/test/markbet/.nuxt/dev/index.mjs:468:20
> [Vue Router warn]: No match found for location with path "/favicon.ico"
> [Vue Router warn]: No match found for location with path "/favicon.ico"
> [nitro] [dev] [unhandledRejection] TypeError: _ctx.$t is not a function
>     at file:///c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:11407:92
>     at renderFnWithContext (c:\tmp\test\markbet\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:847:21)
>     at Module.renderSlot (c:\tmp\test\markbet\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:2958:55)
>     at file:///c:/tmp/test/markbet/.nuxt/dist/server/server.mjs:3450:35
>     at Proxy.renderFnWithContext (c:\tmp\test\markbet\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:847:21)
>     at Proxy.<anonymous> (c:\tmp\test\markbet\node_modules\vue-router\dist\vue-router.cjs.js:2166:60)
>     at renderComponentRoot (c:\tmp\test\markbet\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:890:44)
>     at renderComponentSubTree (c:\tmp\test\markbet\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:259:51)    at renderComponentVNode (c:\tmp\test\markbet\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:188:16)
>     at renderVNode (c:\tmp\test\markbet\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:295:22)

**Comment by florianbgt** [comment]
I just updated the readme. Do you have nodejs 16 installed?
I use yarn, not npm. You can give it a try but npm should work

**Comment by kkurt** [comment]
Yes, i am using nodejs 16.5.1. I also tried yarn... Same error occured.

**Comment by florianbgt** [comment]
Try deleting the yarn.lock, the node modules and run `yarn cache clean -all`.
Are you able to setup a fresh nuxt 3 project from here? https://v3.nuxtjs.org/getting-started/quick-start
Should not mattered but I am using ubuntu 22.04 in case it can help you troubleshooting
